## USDA Food Database

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import json
db = json.load(open('datasets/usda_food/database.json'))
len(db)

6636

In [4]:
db[0].keys()

dict_keys(['id', 'description', 'tags', 'manufacturer', 'group', 'portions', 'nutrients'])

In [5]:
cols = ['id', 'group','description','manufacturer']
info = pd.DataFrame(db, columns=cols)
info

,id,group,description,manufacturer
0,1008,Dairy and Egg Products,"Cheese, caraway",
1,1009,Dairy and Egg Products,"Cheese, cheddar",
2,1018,Dairy and Egg Products,"Cheese, edam",
3,1019,Dairy and Egg Products,"Cheese, feta",
4,1028,Dairy and Egg Products,"Cheese, mozzarella, part skim milk",
...,...,...,...,...
6631,42161,Sausages and Luncheon Meats,"Bologna, beef, low fat",
6632,42173,Sausages and Luncheon Meats,"Turkey and pork sausage, fresh, bulk, patty or...",
6633,43408,Baby Foods,"Babyfood, juice, pear",None
6634,43539,Baby Foods,"Babyfood, dessert, banana yogurt, strained",None
6635,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None

In [6]:
info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6636 entries, 0 to 6635
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6636 non-null   int64
 1   group         6636 non-null   object
 2   description   6636 non-null   object
 3   manufacturer  5195 non-null   object
dtypes: int64(1), object(3)
memory usage: 207.5+ KB

In [7]:
info.group.value_counts()

Vegetables and Vegetable Products    812
Beef Products                        618
Baked Products                       496
Breakfast Cereals                    403
Fast Foods                           365
Legumes and Legume Products          365
Lamb, Veal, and Game Products        345
Sweets                               341
Fruits and Fruit Juices              328
Pork Products                        328
Beverages                            278
Soups, Sauces, and Gravies           275
Finfish and Shellfish Products       255
Baby Foods                           209
Cereal Grains and Pasta              183
Ethnic Foods                         165
Snacks                               162
Nut and Seed Products                128
Poultry Products                     116
Sausages and Luncheon Meats          111
Dairy and Egg Products               107
Fats and Oils                         97
Meals, Entrees, and Sidedishes        57
Restaurant Foods                      51
Spices and Herbs                      41
Name: group, dtype: int64

In [8]:
pd.DataFrame(db[0]['nutrients'])

       value units                         description        group
0     25.180     g                             Protein  Composition
1     29.200     g                   Total lipid (fat)  Composition
2      3.060     g         Carbohydrate, by difference  Composition
3      3.280     g                                 Ash        Other
4    376.000  kcal                              Energy       Energy
..       ...   ...                                 ...          ...
157    1.472     g                              Serine  Amino Acids
158   93.000    mg                         Cholesterol        Other
159   18.584     g        Fatty acids, total saturated        Other
160    8.275     g  Fatty acids, total monounsaturated        Other
161    0.830     g  Fatty acids, total polyunsaturated        Other

[162 rows x 4 columns]

In [9]:
db[0]

{'id': 1008,
 'description': 'Cheese, caraway',
 'tags': [],
 'manufacturer': '',
 'group': 'Dairy and Egg Products',
 'portions': [{'amount': 1, 'unit': 'oz', 'grams': 28.35}],
 'nutrients': [{'value': 25.18,
   'units': 'g',
   'description': 'Protein',
   'group': 'Composition'},
  {'value': 29.2,
   'units': 'g',
   'description': 'Total lipid (fat)',
   'group': 'Composition'},
  {'value': 3.06,
   'units': 'g',
   'description': 'Carbohydrate, by difference',
   'group': 'Composition'},
  {'value': 3.28, 'units': 'g', 'description': 'Ash', 'group': 'Other'},
  {'value': 376.0,
   'units': 'kcal',
   'description': 'Energy',
   'group': 'Energy'},
  {'value': 39.28,
   'units': 'g',
   'description': 'Water',
   'group': 'Composition'},
  {'value': 1573.0, 'units': 'kJ', 'description': 'Energy', 'group': 'Energy'},
  {'value': 0.0,
   'units': 'g',
   'description': 'Fiber, total dietary',
   'group': 'Composition'},
  {'value': 673.0,
   'units': 'mg',
   'description': 'Calcium, Ca',
   'group': 'Elements'},
  {'value': 0.64,
   'units': 'mg',
   'description': 'Iron, Fe',
   'group': 'Elements'},
  {'value': 22.0,
   'units': 'mg',
   'description': 'Magnesium, Mg',
   'group': 'Elements'},
  {'value': 490.0,
   'units': 'mg',
   'description': 'Phosphorus, P',
   'group': 'Elements'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Potassium, K',
   'group': 'Elements'},
  {'value': 690.0,
   'units': 'mg',
   'description': 'Sodium, Na',
   'group': 'Elements'},
  {'value': 2.94,
   'units': 'mg',
   'description': 'Zinc, Zn',
   'group': 'Elements'},
  {'value': 0.024,
   'units': 'mg',
   'description': 'Copper, Cu',
   'group': 'Elements'},
  {'value': 0.021,
   'units': 'mg',
   'description': 'Manganese, Mn',
   'group': 'Elements'},
  {'value': 14.5,
   'units': 'mcg',
   'description': 'Selenium, Se',
   'group': 'Elements'},
  {'value': 1054.0,
   'units': 'IU',
   'description': 'Vitamin A, IU',
   'group': 'Vitamins'},
  {'value': 262.0,
   'units': 'mcg',
   'description': 'Retinol',
   'group': 'Vitamins'},
  {'value': 271.0,
   'units': 'mcg_RAE',
   'description': 'Vitamin A, RAE',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mg',
   'description': 'Vitamin C, total ascorbic acid',
   'group': 'Vitamins'},
  {'value': 0.031,
   'units': 'mg',
   'description': 'Thiamin',
   'group': 'Vitamins'},
  {'value': 0.45,
   'units': 'mg',
   'description': 'Riboflavin',
   'group': 'Vitamins'},
  {'value': 0.18, 'units': 'mg', 'description': 'Niacin', 'group': 'Vitamins'},
  {'value': 0.19,
   'units': 'mg',
   'description': 'Pantothenic acid',
   'group': 'Vitamins'},
  {'value': 0.074,
   'units': 'mg',
   'description': 'Vitamin B-6',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, total',
   'group': 'Vitamins'},
  {'value': 0.27,
   'units': 'mcg',
   'description': 'Vitamin B-12',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mcg',
   'description': 'Folic acid',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, food',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg_DFE',
   'description': 'Folate, DFE',
   'group': 'Vitamins'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Cholesterol',
   'group': 'Other'},
  {'value': 18.584,
   'units': 'g',
   'description': 'Fatty acids, total saturated',
   'group': 'Other'},
  {'value': 8.275,
   'units': 'g',
   'description': 'Fatty acids, total monounsaturated',
   'group': 'Other'},
  {'value': 0.83,
   'units': 'g',
   'description': 'Fatty acids, total polyunsaturated',
   'group': 'Other'},
  {'value': 0.324,
   'units': 'g',
   'description': 'Tryptophan',
   'group': 'Amino Acids'},
  {'value': 0.896,
   'units': 'g',
   'description': 'Threonine',
   'group': 'Amino Acids'},
  {'value': 1.563,
   'units': 'g',
   'description': 'Isoleucine',
   'group': 'Amino Acids'},
  {'value': 2.412,
   'units': 'g',
   'description': 'Leucine',
   'group': 'Amino Acids'},
  {'value': 2.095,
   'units': 'g',
   'description': 'Lysine',
   'group': 'Amino Acids'},
  {'value': 0.659,
   'units': 'g',
   'description': 'Methionine',
   'group': 'Amino Acids'},
  {'value': 0.126,
   'units': 'g',
   'description': 'Cystine',
   'group': 'Amino Acids'},
  {'value': 1.326,
   'units': 'g',
   'description': 'Phenylalanine',
   'group': 'Amino Acids'},
  {'value': 1.216,
   'units': 'g',
   'description': 'Tyrosine',
   'group': 'Amino Acids'},
  {'value': 1.682,
   'units': 'g',
   'description': 'Valine',
   'group': 'Amino Acids'},
  {'value': 0.952,
   'units': 'g',
   'description': 'Arginine',
   'group': 'Amino Acids'},
  {'value': 0.884,
   'units': 'g',
   'description': 'Histidine',
   'group': 'Amino Acids'},
  {'value': 0.711,
   'units': 'g',
   'description': 'Alanine',
   'group': 'Amino Acids'},
  {'value': 1.618,
   'units': 'g',
   'description': 'Aspartic acid',
   'group': 'Amino Acids'},
  {'value': 6.16,
   'units': 'g',
   'description': 'Glutamic acid',
   'group': 'Amino Acids'},
  {'value': 0.439,
   'units': 'g',
   'description': 'Glycine',
   'group': 'Amino Acids'},
  {'value': 2.838,
   'units': 'g',
   'description': 'Proline',
   'group': 'Amino Acids'},
  {'value': 1.472,
   'units': 'g',
   'description': 'Serine',
   'group': 'Amino Acids'},
  {'value': 25.18,
   'units': 'g',
   'description': 'Protein',
   'group': 'Composition'},
  {'value': 29.2,
   'units': 'g',
   'description': 'Total lipid (fat)',
   'group': 'Composition'},
  {'value': 3.06,
   'units': 'g',
   'description': 'Carbohydrate, by difference',
   'group': 'Composition'},
  {'value': 3.28, 'units': 'g', 'description': 'Ash', 'group': 'Other'},
  {'value': 376.0,
   'units': 'kcal',
   'description': 'Energy',
   'group': 'Energy'},
  {'value': 39.28,
   'units': 'g',
   'description': 'Water',
   'group': 'Composition'},
  {'value': 1573.0, 'units': 'kJ', 'description': 'Energy', 'group': 'Energy'},
  {'value': 0.0,
   'units': 'g',
   'description': 'Fiber, total dietary',
   'group': 'Composition'},
  {'value': 673.0,
   'units': 'mg',
   'description': 'Calcium, Ca',
   'group': 'Elements'},
  {'value': 0.64,
   'units': 'mg',
   'description': 'Iron, Fe',
   'group': 'Elements'},
  {'value': 22.0,
   'units': 'mg',
   'description': 'Magnesium, Mg',
   'group': 'Elements'},
  {'value': 490.0,
   'units': 'mg',
   'description': 'Phosphorus, P',
   'group': 'Elements'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Potassium, K',
   'group': 'Elements'},
  {'value': 690.0,
   'units': 'mg',
   'description': 'Sodium, Na',
   'group': 'Elements'},
  {'value': 2.94,
   'units': 'mg',
   'description': 'Zinc, Zn',
   'group': 'Elements'},
  {'value': 0.024,
   'units': 'mg',
   'description': 'Copper, Cu',
   'group': 'Elements'},
  {'value': 0.021,
   'units': 'mg',
   'description': 'Manganese, Mn',
   'group': 'Elements'},
  {'value': 14.5,
   'units': 'mcg',
   'description': 'Selenium, Se',
   'group': 'Elements'},
  {'value': 1054.0,
   'units': 'IU',
   'description': 'Vitamin A, IU',
   'group': 'Vitamins'},
  {'value': 262.0,
   'units': 'mcg',
   'description': 'Retinol',
   'group': 'Vitamins'},
  {'value': 271.0,
   'units': 'mcg_RAE',
   'description': 'Vitamin A, RAE',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mg',
   'description': 'Vitamin C, total ascorbic acid',
   'group': 'Vitamins'},
  {'value': 0.031,
   'units': 'mg',
   'description': 'Thiamin',
   'group': 'Vitamins'},
  {'value': 0.45,
   'units': 'mg',
   'description': 'Riboflavin',
   'group': 'Vitamins'},
  {'value': 0.18, 'units': 'mg', 'description': 'Niacin', 'group': 'Vitamins'},
  {'value': 0.19,
   'units': 'mg',
   'description': 'Pantothenic acid',
   'group': 'Vitamins'},
  {'value': 0.074,
   'units': 'mg',
   'description': 'Vitamin B-6',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, total',
   'group': 'Vitamins'},
  {'value': 0.27,
   'units': 'mcg',
   'description': 'Vitamin B-12',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mcg',
   'description': 'Folic acid',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, food',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg_DFE',
   'description': 'Folate, DFE',
   'group': 'Vitamins'},
  {'value': 0.324,
   'units': 'g',
   'description': 'Tryptophan',
   'group': 'Amino Acids'},
  {'value': 0.896,
   'units': 'g',
   'description': 'Threonine',
   'group': 'Amino Acids'},
  {'value': 1.563,
   'units': 'g',
   'description': 'Isoleucine',
   'group': 'Amino Acids'},
  {'value': 2.412,
   'units': 'g',
   'description': 'Leucine',
   'group': 'Amino Acids'},
  {'value': 2.095,
   'units': 'g',
   'description': 'Lysine',
   'group': 'Amino Acids'},
  {'value': 0.659,
   'units': 'g',
   'description': 'Methionine',
   'group': 'Amino Acids'},
  {'value': 0.126,
   'units': 'g',
   'description': 'Cystine',
   'group': 'Amino Acids'},
  {'value': 1.326,
   'units': 'g',
   'description': 'Phenylalanine',
   'group': 'Amino Acids'},
  {'value': 1.216,
   'units': 'g',
   'description': 'Tyrosine',
   'group': 'Amino Acids'},
  {'value': 1.682,
   'units': 'g',
   'description': 'Valine',
   'group': 'Amino Acids'},
  {'value': 0.952,
   'units': 'g',
   'description': 'Arginine',
   'group': 'Amino Acids'},
  {'value': 0.884,
   'units': 'g',
   'description': 'Histidine',
   'group': 'Amino Acids'},
  {'value': 0.711,
   'units': 'g',
   'description': 'Alanine',
   'group': 'Amino Acids'},
  {'value': 1.618,
   'units': 'g',
   'description': 'Aspartic acid',
   'group': 'Amino Acids'},
  {'value': 6.16,
   'units': 'g',
   'description': 'Glutamic acid',
   'group': 'Amino Acids'},
  {'value': 0.439,
   'units': 'g',
   'description': 'Glycine',
   'group': 'Amino Acids'},
  {'value': 2.838,
   'units': 'g',
   'description': 'Proline',
   'group': 'Amino Acids'},
  {'value': 1.472,
   'units': 'g',
   'description': 'Serine',
   'group': 'Amino Acids'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Cholesterol',
   'group': 'Other'},
  {'value': 18.584,
   'units': 'g',
   'description': 'Fatty acids, total saturated',
   'group': 'Other'},
  {'value': 8.275,
   'units': 'g',
   'description': 'Fatty acids, total monounsaturated',
   'group': 'Other'},
  {'value': 0.83,
   'units': 'g',
   'description': 'Fatty acids, total polyunsaturated',
   'group': 'Other'},
  {'value': 25.18,
   'units': 'g',
   'description': 'Protein',
   'group': 'Composition'},
  {'value': 29.2,
   'units': 'g',
   'description': 'Total lipid (fat)',
   'group': 'Composition'},
  {'value': 3.06,
   'units': 'g',
   'description': 'Carbohydrate, by difference',
   'group': 'Composition'},
  {'value': 3.28, 'units': 'g', 'description': 'Ash', 'group': 'Other'},
  {'value': 376.0,
   'units': 'kcal',
   'description': 'Energy',
   'group': 'Energy'},
  {'value': 39.28,
   'units': 'g',
   'description': 'Water',
   'group': 'Composition'},
  {'value': 1573.0, 'units': 'kJ', 'description': 'Energy', 'group': 'Energy'},
  {'value': 0.0,
   'units': 'g',
   'description': 'Fiber, total dietary',
   'group': 'Composition'},
  {'value': 673.0,
   'units': 'mg',
   'description': 'Calcium, Ca',
   'group': 'Elements'},
  {'value': 0.64,
   'units': 'mg',
   'description': 'Iron, Fe',
   'group': 'Elements'},
  {'value': 22.0,
   'units': 'mg',
   'description': 'Magnesium, Mg',
   'group': 'Elements'},
  {'value': 490.0,
   'units': 'mg',
   'description': 'Phosphorus, P',
   'group': 'Elements'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Potassium, K',
   'group': 'Elements'},
  {'value': 690.0,
   'units': 'mg',
   'description': 'Sodium, Na',
   'group': 'Elements'},
  {'value': 2.94,
   'units': 'mg',
   'description': 'Zinc, Zn',
   'group': 'Elements'},
  {'value': 0.024,
   'units': 'mg',
   'description': 'Copper, Cu',
   'group': 'Elements'},
  {'value': 0.021,
   'units': 'mg',
   'description': 'Manganese, Mn',
   'group': 'Elements'},
  {'value': 14.5,
   'units': 'mcg',
   'description': 'Selenium, Se',
   'group': 'Elements'},
  {'value': 1054.0,
   'units': 'IU',
   'description': 'Vitamin A, IU',
   'group': 'Vitamins'},
  {'value': 262.0,
   'units': 'mcg',
   'description': 'Retinol',
   'group': 'Vitamins'},
  {'value': 271.0,
   'units': 'mcg_RAE',
   'description': 'Vitamin A, RAE',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mg',
   'description': 'Vitamin C, total ascorbic acid',
   'group': 'Vitamins'},
  {'value': 0.031,
   'units': 'mg',
   'description': 'Thiamin',
   'group': 'Vitamins'},
  {'value': 0.45,
   'units': 'mg',
   'description': 'Riboflavin',
   'group': 'Vitamins'},
  {'value': 0.18, 'units': 'mg', 'description': 'Niacin', 'group': 'Vitamins'},
  {'value': 0.19,
   'units': 'mg',
   'description': 'Pantothenic acid',
   'group': 'Vitamins'},
  {'value': 0.074,
   'units': 'mg',
   'description': 'Vitamin B-6',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, total',
   'group': 'Vitamins'},
  {'value': 0.27,
   'units': 'mcg',
   'description': 'Vitamin B-12',
   'group': 'Vitamins'},
  {'value': 0.0,
   'units': 'mcg',
   'description': 'Folic acid',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg',
   'description': 'Folate, food',
   'group': 'Vitamins'},
  {'value': 18.0,
   'units': 'mcg_DFE',
   'description': 'Folate, DFE',
   'group': 'Vitamins'},
  {'value': 0.324,
   'units': 'g',
   'description': 'Tryptophan',
   'group': 'Amino Acids'},
  {'value': 0.896,
   'units': 'g',
   'description': 'Threonine',
   'group': 'Amino Acids'},
  {'value': 1.563,
   'units': 'g',
   'description': 'Isoleucine',
   'group': 'Amino Acids'},
  {'value': 2.412,
   'units': 'g',
   'description': 'Leucine',
   'group': 'Amino Acids'},
  {'value': 2.095,
   'units': 'g',
   'description': 'Lysine',
   'group': 'Amino Acids'},
  {'value': 0.659,
   'units': 'g',
   'description': 'Methionine',
   'group': 'Amino Acids'},
  {'value': 0.126,
   'units': 'g',
   'description': 'Cystine',
   'group': 'Amino Acids'},
  {'value': 1.326,
   'units': 'g',
   'description': 'Phenylalanine',
   'group': 'Amino Acids'},
  {'value': 1.216,
   'units': 'g',
   'description': 'Tyrosine',
   'group': 'Amino Acids'},
  {'value': 1.682,
   'units': 'g',
   'description': 'Valine',
   'group': 'Amino Acids'},
  {'value': 0.952,
   'units': 'g',
   'description': 'Arginine',
   'group': 'Amino Acids'},
  {'value': 0.884,
   'units': 'g',
   'description': 'Histidine',
   'group': 'Amino Acids'},
  {'value': 0.711,
   'units': 'g',
   'description': 'Alanine',
   'group': 'Amino Acids'},
  {'value': 1.618,
   'units': 'g',
   'description': 'Aspartic acid',
   'group': 'Amino Acids'},
  {'value': 6.16,
   'units': 'g',
   'description': 'Glutamic acid',
   'group': 'Amino Acids'},
  {'value': 0.439,
   'units': 'g',
   'description': 'Glycine',
   'group': 'Amino Acids'},
  {'value': 2.838,
   'units': 'g',
   'description': 'Proline',
   'group': 'Amino Acids'},
  {'value': 1.472,
   'units': 'g',
   'description': 'Serine',
   'group': 'Amino Acids'},
  {'value': 93.0,
   'units': 'mg',
   'description': 'Cholesterol',
   'group': 'Other'},
  {'value': 18.584,
   'units': 'g',
   'description': 'Fatty acids, total saturated',
   'group': 'Other'},
  {'value': 8.275,
   'units': 'g',
   'description': 'Fatty acids, total monounsaturated',
   'group': 'Other'},
  {'value': 0.83,
   'units': 'g',
   'description': 'Fatty acids, total polyunsaturated',
   'group': 'Other'}]}

In [10]:
nutrients = pd.DataFrame(columns=['value','units','description','group','id'])
for row in db:
    ntr = pd.DataFrame(row['nutrients'])
    ntr['id'] = row['id']
    nutrients = pd.concat([nutrients, ntr], ignore_index=True)

In [11]:
nutrients.shape

(389355, 5)

In [12]:
nutrients.duplicated().sum()

14179

In [13]:
nutrients.drop_duplicates(inplace=True, ignore_index=True)
nutrients.columns = ['value','units','nutrient','nutgroup','id']
ndata = pd.merge(nutrients, info, on='id', how='outer')

In [14]:
ndata

,value,units,nutrient,nutgroup,id,group,description,manufacturer
0,25.180,g,Protein,Composition,1008,Dairy and Egg Products,"Cheese, caraway",
1,29.200,g,Total lipid (fat),Composition,1008,Dairy and Egg Products,"Cheese, caraway",
2,3.060,g,"Carbohydrate, by difference",Composition,1008,Dairy and Egg Products,"Cheese, caraway",
3,3.280,g,Ash,Other,1008,Dairy and Egg Products,"Cheese, caraway",
4,376.000,kcal,Energy,Energy,1008,Dairy and Egg Products,"Cheese, caraway",
...,...,...,...,...,...,...,...,...
375171,0.000,mcg,"Vitamin B-12, added",Vitamins,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None
375172,0.000,mg,Cholesterol,Other,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None
375173,0.072,g,"Fatty acids, total saturated",Other,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None
375174,0.028,g,"Fatty acids, total monounsaturated",Other,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None
375175,0.041,g,"Fatty acids, total polyunsaturated",Other,43546,Baby Foods,"Babyfood, banana no tapioca, strained",None

In [15]:
ndata.iloc[0]

value                            25.18
units                                g
nutrient                       Protein
nutgroup                   Composition
id                                1008
group           Dairy and Egg Products
description            Cheese, caraway
manufacturer
Name: 0, dtype: object

In [16]:
results = ndata.groupby(['group','nutrient'])['value'].quantile(0.5)
results

group                              nutrient
Baby Foods                         Alanine                          0.085
                                   Alcohol, ethyl                   0.000
                                   Arginine                         0.104
                                   Ash                              0.620
                                   Aspartic acid                    0.220
                                                                    ...
Vegetables and Vegetable Products  Vitamin E (alpha-tocopherol)     0.290
                                   Vitamin E, added                 0.000
                                   Vitamin K (phylloquinone)        9.000
                                   Water                           89.195
                                   Zinc, Zn                         0.330
Name: value, Length: 2246, dtype: float64

In [17]:
def get_max(group):
    idx = group.index[group['value']==group['value'].max()]
    return group.loc[idx]['description']

In [18]:
max_food = ndata.groupby(['nutrient','nutgroup']).apply(get_max).reset_index()

In [19]:
max_food

,nutrient,nutgroup,level_2,description
0,Adjusted Protein,Composition,197743,"Baking chocolate, unsweetened, squares"
1,Alanine,Amino Acids,202227,"Gelatins, dry powder, unsweetened"
2,"Alcohol, ethyl",Other,324645,"Alcoholic beverage, distilled, all (gin, rum, ..."
3,Arginine,Amino Acids,128415,"Seeds, sesame flour, low-fat"
4,Ash,Other,204242,"Desserts, rennin, tablets, unsweetened"
...,...,...,...,...
146,Water,Composition,322993,"Water, bottled, POLAND SPRING"
147,Water,Composition,324209,"Water, bottled, non-carbonated, CALISTOGA"
148,Water,Composition,324221,"Water, bottled, non-carbonated, CRYSTAL GEYSER"
149,Water,Composition,324233,"Water, bottled, non-carbonated, NAYA"
150,"Zinc, Zn",Elements,333726,"Mollusks, oyster, eastern, canned"

In [20]:
max_food[max_food['nutgroup']=='Amino Acids']

,nutrient,nutgroup,level_2,description
1,Alanine,Amino Acids,202227,"Gelatins, dry powder, unsweetened"
3,Arginine,Amino Acids,128415,"Seeds, sesame flour, low-fat"
5,Aspartic acid,Amino Acids,158588,Soy protein isolate
6,Aspartic acid,Amino Acids,164163,"Soy protein isolate, potassium type"
7,Aspartic acid,Amino Acids,164230,"Soy protein isolate, potassium type, crude pro..."
21,Cystine,Amino Acids,127716,"Seeds, cottonseed flour, low fat (glandless)"
45,Glutamic acid,Amino Acids,158589,Soy protein isolate
46,Glutamic acid,Amino Acids,164164,"Soy protein isolate, potassium type"
47,Glutamic acid,Amino Acids,164231,"Soy protein isolate, potassium type, crude pro..."
48,Glycine,Amino Acids,202230,"Gelatins, dry powder, unsweetened"
49,Histidine,Amino Acids,261289,"Whale, beluga, meat, dried (Alaska Native)"
50,Hydroxyproline,Amino Acids,242502,"KENTUCKY FRIED CHICKEN, Fried Chicken, ORIGINA..."
52,Isoleucine,Amino Acids,160033,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
57,Leucine,Amino Acids,160034,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
60,Lysine,Amino Acids,262042,"Seal, bearded (Oogruk), meat, dried (Alaska Na..."
66,Methionine,Amino Acids,325782,"Fish, cod, Atlantic, dried and salted"
69,Phenylalanine,Amino Acids,160038,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
73,Proline,Amino Acids,202231,"Gelatins, dry powder, unsweetened"
78,Serine,Amino Acids,160048,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
86,Threonine,Amino Acids,160032,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
87,Threonine,Amino Acids,160082,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
128,Tryptophan,Amino Acids,266979,"Sea lion, Steller, meat with fat (Alaska Native)"
129,Tyrosine,Amino Acids,160039,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
130,Tyrosine,Amino Acids,160089,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."
131,Valine,Amino Acids,160040,"Soy protein isolate, PROTEIN TECHNOLOGIES INTE..."